source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CheckMobiSwift_Example', :exclusive => true do
  pod "CheckMobiSwift", :path => "../"
end

target 'CheckMobiSwift_Tests', :exclusive => true do
  pod "CheckMobiSwift", :path => "../"

  
end
